# Generated by Django 4.1.7 on 2023-03-30 17:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='Не указан', max_length=100)),
                ('text', models.TextField(max_length=10000)),
                ('translation', models.TextField(max_length=10000)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 3, 30, 17, 2, 7, 640848, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
