# Generated by Django 4.1.7 on 2023-04-10 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0002_alter_translation_date_wordbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 17, 4, 18, 955490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 17, 4, 18, 956491, tzinfo=datetime.timezone.utc)),
        ),
    ]
