# Generated by Django 4.1.7 on 2023-04-13 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0003_alter_translation_date_alter_wordbook_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='lan1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wordbook',
            name='lan2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 19, 34, 20, 577812, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 19, 34, 20, 578901, tzinfo=datetime.timezone.utc)),
        ),
    ]
