# Generated by Django 4.1.7 on 2023-04-13 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0004_wordbook_lan1_wordbook_lan2_alter_translation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordbook',
            name='lan1',
        ),
        migrations.RemoveField(
            model_name='wordbook',
            name='lan2',
        ),
        migrations.AlterField(
            model_name='translation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 19, 48, 8, 763143, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 19, 48, 8, 763143, tzinfo=datetime.timezone.utc)),
        ),
    ]
